export interface TestEntry {
  name: string
  abbreviations: string[]
  synonyms: string[]
  category: string
}

export const CLINICAL_CATEGORIES: { name: string; tests: string[] }[] = [
  {
    name: 'Hematology',
    tests: [
      'Complete Blood Count (CBC)',
      'Peripheral Blood Smear',
      'Reticulocyte Count',
      'Erythrocyte Sedimentation Rate (ESR)',
      'C-Reactive Protein (CRP)',
    ],
  },
  {
    name: 'Metabolic & Chemistry',
    tests: [
      'Basic Metabolic Panel (BMP)',
      'Comprehensive Metabolic Panel (CMP)',
      'Liver Function Tests (LFTs)',
      'Lipid Panel',
      'Serum Albumin',
      'Serum Protein Electrophoresis (SPEP)',
      'Uric Acid',
      'Lactate Dehydrogenase (LDH)',
      'Thyroid Stimulating Hormone (TSH)',
      'Free T4',
      'Hemoglobin A1c (HbA1c)',
      'Fasting Glucose',
      'Serum Calcium',
      'Serum Phosphorus',
      'Serum Magnesium',
      'Serum Iron / TIBC / Ferritin',
      'Vitamin B12 / Folate',
    ],
  },
  {
    name: 'Urinalysis & Renal',
    tests: [
      'Urinalysis with Microscopy',
      'Urine Culture and Sensitivity',
      'Spot Urine Protein-to-Creatinine Ratio',
      '24-Hour Urine Protein',
      '24-Hour Urine Creatinine Clearance',
      'Urine Albumin-to-Creatinine Ratio',
      'Urine Electrolytes (Na, K, Cl)',
    ],
  },
  {
    name: 'Coagulation',
    tests: [
      'Prothrombin Time (PT) / INR',
      'Partial Thromboplastin Time (PTT)',
      'D-Dimer',
      'Fibrinogen',
      'Bleeding Time',
    ],
  },
  {
    name: 'Immunology & Serology',
    tests: [
      'Antinuclear Antibody (ANA)',
      'Anti-dsDNA Antibody',
      'Anti-Smith Antibody',
      'Complement Levels (C3, C4)',
      'Rheumatoid Factor (RF)',
      'Anti-CCP Antibody',
      'ANCA (c-ANCA / p-ANCA)',
      'Anti-GBM Antibody',
      'Cryoglobulins',
      'Serum Immunoglobulins (IgG, IgA, IgM)',
    ],
  },
  {
    name: 'Infectious Disease',
    tests: [
      'Blood Culture x2',
      'HIV Antibody / Antigen (4th Gen)',
      'Hepatitis B Surface Antigen',
      'Hepatitis C Antibody',
      'RPR / VDRL (Syphilis)',
      'Monospot Test',
      'Strep Throat Culture',
      'Urine Legionella Antigen',
      'Urine Pneumococcal Antigen',
      'COVID-19 PCR',
      'Influenza A/B PCR',
      'Tuberculin Skin Test (PPD)',
      'QuantiFERON-TB Gold',
    ],
  },
  {
    name: 'Cardiac',
    tests: [
      'Troponin I or T (high sensitivity)',
      'BNP / NT-proBNP',
      'CK-MB',
      'Myoglobin',
      'Digoxin Level',
      'Lipase / Amylase',
    ],
  },
  {
    name: 'Toxicology & Drug Levels',
    tests: [
      'Urine Drug Screen (UDS)',
      'Blood Alcohol Level (BAL)',
      'Acetaminophen Level',
      'Salicylate Level',
      'Vancomycin Trough',
      'Phenytoin Level',
      'Lithium Level',
    ],
  },
  {
    name: 'Arterial Blood Gas & Respiratory',
    tests: [
      'Arterial Blood Gas (ABG)',
      'Pulse Oximetry (SpO2)',
      'Peak Flow',
      'Sputum Culture and Sensitivity',
      'Sputum Gram Stain',
    ],
  },
  {
    name: 'Imaging',
    tests: [
      'Chest X-Ray (PA and Lateral)',
      'CT Chest without Contrast',
      'CT Chest with Contrast',
      'CT Abdomen and Pelvis without Contrast',
      'CT Abdomen and Pelvis with Contrast',
      'CT Head without Contrast',
      'MRI Brain with and without Contrast',
      'MRI Spine',
      'Renal Ultrasound',
      'Abdominal Ultrasound',
      'Pelvic Ultrasound',
      'Echocardiogram (Transthoracic)',
      'Echocardiogram (Transesophageal)',
      'Venous Doppler Ultrasound Bilateral Lower Extremities',
      'V/Q Scan',
      'CT Pulmonary Angiography (CTPA)',
      'Bone Scan',
      'DEXA Scan',
    ],
  },
  {
    name: 'Procedures & Special Tests',
    tests: [
      'Electrocardiogram (ECG/EKG)',
      'Holter Monitor (24-hour)',
      'Stress Test (Exercise Treadmill)',
      'Lumbar Puncture (CSF Analysis)',
      'Bone Marrow Biopsy',
      'Skin Biopsy',
      'Renal Biopsy',
      'Liver Biopsy',
      'Colonoscopy',
      'Upper Endoscopy (EGD)',
      'Bronchoscopy',
      'Spirometry / PFTs',
      'Nerve Conduction Study (NCS)',
      'EMG',
    ],
  },
]

export const MASTER_TEST_LIST: TestEntry[] = [
  // ── HEMATOLOGY ──
  { name: 'Complete Blood Count (CBC)', abbreviations: ['CBC'], synonyms: ['complete blood count', 'blood count', 'hemogram', 'full blood count'], category: 'Hematology' },
  { name: 'Peripheral Blood Smear', abbreviations: ['PBS'], synonyms: ['blood smear', 'peripheral smear', 'blood film'], category: 'Hematology' },
  { name: 'Reticulocyte Count', abbreviations: ['retic'], synonyms: ['reticulocyte count', 'retic count', 'immature red cells'], category: 'Hematology' },
  { name: 'Erythrocyte Sedimentation Rate (ESR)', abbreviations: ['ESR', 'sed rate'], synonyms: ['erythrocyte sedimentation rate', 'sedimentation rate', 'sed rate', 'inflammation marker'], category: 'Hematology' },
  { name: 'C-Reactive Protein (CRP)', abbreviations: ['CRP'], synonyms: ['c-reactive protein', 'crp', 'inflammation marker', 'acute phase reactant'], category: 'Hematology' },

  // ── METABOLIC & CHEMISTRY ──
  { name: 'Basic Metabolic Panel (BMP)', abbreviations: ['BMP'], synonyms: ['basic metabolic panel', 'basic metabolic', 'kidney function', 'electrolytes', 'renal panel', 'bmp', 'sodium potassium'], category: 'Metabolic & Chemistry' },
  { name: 'Comprehensive Metabolic Panel (CMP)', abbreviations: ['CMP'], synonyms: ['comprehensive metabolic panel', 'comprehensive metabolic', 'kidney function', 'liver function', 'electrolytes', 'cmp', 'metabolic panel'], category: 'Metabolic & Chemistry' },
  { name: 'Liver Function Tests (LFTs)', abbreviations: ['LFTs', 'LFT'], synonyms: ['liver function tests', 'liver function', 'liver panel', 'hepatic panel', 'lfts', 'alt ast bilirubin'], category: 'Metabolic & Chemistry' },
  { name: 'Lipid Panel', abbreviations: [], synonyms: ['lipid panel', 'cholesterol', 'triglycerides', 'hdl ldl', 'lipids', 'cardiovascular risk'], category: 'Metabolic & Chemistry' },
  { name: 'Serum Albumin', abbreviations: [], synonyms: ['albumin', 'serum albumin', 'nutrition marker', 'protein'], category: 'Metabolic & Chemistry' },
  { name: 'Serum Protein Electrophoresis (SPEP)', abbreviations: ['SPEP'], synonyms: ['protein electrophoresis', 'spep', 'serum protein electrophoresis', 'm-spike', 'paraprotein', 'myeloma screen'], category: 'Metabolic & Chemistry' },
  { name: 'Uric Acid', abbreviations: [], synonyms: ['uric acid', 'urate', 'gout', 'hyperuricemia'], category: 'Metabolic & Chemistry' },
  { name: 'Lactate Dehydrogenase (LDH)', abbreviations: ['LDH'], synonyms: ['lactate dehydrogenase', 'ldh', 'tissue damage marker', 'hemolysis marker'], category: 'Metabolic & Chemistry' },
  { name: 'Thyroid Stimulating Hormone (TSH)', abbreviations: ['TSH'], synonyms: ['thyroid stimulating hormone', 'tsh', 'thyroid function', 'thyroid'], category: 'Metabolic & Chemistry' },
  { name: 'Free T4', abbreviations: ['fT4'], synonyms: ['free t4', 'free thyroxine', 'ft4', 'thyroxine', 'thyroid function'], category: 'Metabolic & Chemistry' },
  { name: 'Hemoglobin A1c (HbA1c)', abbreviations: ['HbA1c', 'A1c', 'HgbA1c'], synonyms: ['hemoglobin a1c', 'glycated hemoglobin', 'a1c', 'hba1c', 'diabetes control', 'glycosylated hemoglobin'], category: 'Metabolic & Chemistry' },
  { name: 'Fasting Glucose', abbreviations: ['FBG', 'FPG'], synonyms: ['fasting glucose', 'blood sugar', 'blood glucose', 'fasting blood sugar', 'diabetes screen'], category: 'Metabolic & Chemistry' },
  { name: 'Serum Calcium', abbreviations: ['Ca'], synonyms: ['serum calcium', 'calcium', 'hypercalcemia', 'hypocalcemia'], category: 'Metabolic & Chemistry' },
  { name: 'Serum Phosphorus', abbreviations: ['Phos'], synonyms: ['serum phosphorus', 'phosphorus', 'phosphate', 'hyperphosphatemia'], category: 'Metabolic & Chemistry' },
  { name: 'Serum Magnesium', abbreviations: ['Mg'], synonyms: ['serum magnesium', 'magnesium', 'hypomagnesemia', 'electrolyte'], category: 'Metabolic & Chemistry' },
  { name: 'Serum Iron / TIBC / Ferritin', abbreviations: ['TIBC'], synonyms: ['iron studies', 'serum iron', 'tibc', 'ferritin', 'iron deficiency', 'iron overload', 'transferrin saturation'], category: 'Metabolic & Chemistry' },
  { name: 'Vitamin B12 / Folate', abbreviations: ['B12'], synonyms: ['vitamin b12', 'folate', 'b12', 'folic acid', 'cobalamin', 'megaloblastic anemia'], category: 'Metabolic & Chemistry' },

  // ── URINALYSIS & RENAL ──
  { name: 'Urinalysis with Microscopy', abbreviations: ['UA', 'U/A'], synonyms: ['urinalysis', 'urine analysis', 'ua', 'urine test', 'urine microscopy', 'urine dipstick', 'urine sediment'], category: 'Urinalysis & Renal' },
  { name: 'Urine Culture and Sensitivity', abbreviations: ['UCx', 'U Cx'], synonyms: ['urine culture', 'urine culture and sensitivity', 'ucx', 'uti culture', 'bacteriuria'], category: 'Urinalysis & Renal' },
  { name: 'Spot Urine Protein-to-Creatinine Ratio', abbreviations: ['PCR', 'uPCR'], synonyms: ['urine protein creatinine ratio', 'upcr', 'protein creatinine ratio', 'spot urine protein', 'proteinuria'], category: 'Urinalysis & Renal' },
  { name: '24-Hour Urine Protein', abbreviations: [], synonyms: ['24 hour urine protein', '24-hour urine', 'urine protein collection', 'timed urine protein', 'proteinuria'], category: 'Urinalysis & Renal' },
  { name: '24-Hour Urine Creatinine Clearance', abbreviations: ['CrCl'], synonyms: ['creatinine clearance', 'crcl', '24 hour urine', 'renal clearance', 'glomerular filtration'], category: 'Urinalysis & Renal' },
  { name: 'Urine Albumin-to-Creatinine Ratio', abbreviations: ['UACR', 'ACR'], synonyms: ['albumin creatinine ratio', 'uacr', 'microalbuminuria', 'urine albumin', 'diabetic nephropathy screen'], category: 'Urinalysis & Renal' },
  { name: 'Urine Electrolytes (Na, K, Cl)', abbreviations: [], synonyms: ['urine electrolytes', 'urine sodium', 'urine potassium', 'urine chloride', 'fena', 'fractional excretion'], category: 'Urinalysis & Renal' },

  // ── COAGULATION ──
  { name: 'Prothrombin Time (PT) / INR', abbreviations: ['PT', 'INR', 'PT/INR'], synonyms: ['prothrombin time', 'pt inr', 'inr', 'coagulation', 'clotting time', 'anticoagulation monitoring', 'warfarin monitoring'], category: 'Coagulation' },
  { name: 'Partial Thromboplastin Time (PTT)', abbreviations: ['PTT', 'aPTT'], synonyms: ['partial thromboplastin time', 'ptt', 'aptt', 'coagulation', 'heparin monitoring', 'clotting'], category: 'Coagulation' },
  { name: 'D-Dimer', abbreviations: [], synonyms: ['d-dimer', 'd dimer', 'clot marker', 'dvt screen', 'pe screen', 'fibrin degradation', 'pulmonary embolism screen'], category: 'Coagulation' },
  { name: 'Fibrinogen', abbreviations: [], synonyms: ['fibrinogen', 'clotting factor', 'coagulation', 'dic', 'disseminated intravascular coagulation'], category: 'Coagulation' },
  { name: 'Bleeding Time', abbreviations: [], synonyms: ['bleeding time', 'platelet function', 'coagulation screen'], category: 'Coagulation' },

  // ── IMMUNOLOGY & SEROLOGY ──
  { name: 'Antinuclear Antibody (ANA)', abbreviations: ['ANA'], synonyms: ['antinuclear antibody', 'ana', 'lupus test', 'autoimmune screen', 'connective tissue disease', 'sle screen'], category: 'Immunology & Serology' },
  { name: 'Anti-dsDNA Antibody', abbreviations: ['anti-dsDNA'], synonyms: ['anti dsdna', 'double stranded dna antibody', 'lupus antibody', 'sle antibody'], category: 'Immunology & Serology' },
  { name: 'Anti-Smith Antibody', abbreviations: ['anti-Sm'], synonyms: ['anti smith', 'anti-sm antibody', 'sle specific antibody'], category: 'Immunology & Serology' },
  { name: 'Complement Levels (C3, C4)', abbreviations: ['C3', 'C4'], synonyms: ['complement levels', 'c3 c4', 'complement', 'lupus complement', 'low complement'], category: 'Immunology & Serology' },
  { name: 'Rheumatoid Factor (RF)', abbreviations: ['RF'], synonyms: ['rheumatoid factor', 'rf', 'rheumatoid arthritis test', 'ra factor'], category: 'Immunology & Serology' },
  { name: 'Anti-CCP Antibody', abbreviations: ['anti-CCP', 'CCP'], synonyms: ['anti ccp', 'anti-citrullinated protein antibody', 'acpa', 'rheumatoid arthritis antibody'], category: 'Immunology & Serology' },
  { name: 'ANCA (c-ANCA / p-ANCA)', abbreviations: ['ANCA', 'c-ANCA', 'p-ANCA'], synonyms: ['anca', 'antineutrophil cytoplasmic antibody', 'vasculitis antibody', 'wegener antibody', 'pr3 mpo'], category: 'Immunology & Serology' },
  { name: 'Anti-GBM Antibody', abbreviations: ['anti-GBM'], synonyms: ['anti gbm', 'anti-glomerular basement membrane', 'goodpasture antibody', 'gbm antibody'], category: 'Immunology & Serology' },
  { name: 'Cryoglobulins', abbreviations: [], synonyms: ['cryoglobulins', 'cryoglobulinemia', 'cold proteins'], category: 'Immunology & Serology' },
  { name: 'Serum Immunoglobulins (IgG, IgA, IgM)', abbreviations: ['Igs'], synonyms: ['immunoglobulins', 'igg iga igm', 'serum immunoglobulins', 'hypogammaglobulinemia', 'hypergammaglobulinemia', 'antibody levels'], category: 'Immunology & Serology' },

  // ── INFECTIOUS DISEASE ──
  { name: 'Blood Culture x2', abbreviations: ['BCx'], synonyms: ['blood culture', 'bacteremia', 'sepsis workup', 'blood cultures', 'bcx'], category: 'Infectious Disease' },
  { name: 'HIV Antibody / Antigen (4th Gen)', abbreviations: ['HIV'], synonyms: ['hiv test', 'hiv antibody', 'hiv antigen', '4th generation hiv', 'aids test', 'hiv screen'], category: 'Infectious Disease' },
  { name: 'Hepatitis B Surface Antigen', abbreviations: ['HBsAg'], synonyms: ['hepatitis b', 'hbsag', 'hep b surface antigen', 'hepatitis b antigen', 'hepatitis screen'], category: 'Infectious Disease' },
  { name: 'Hepatitis C Antibody', abbreviations: ['HCV Ab'], synonyms: ['hepatitis c', 'hcv antibody', 'hep c antibody', 'hepatitis c screen'], category: 'Infectious Disease' },
  { name: 'RPR / VDRL (Syphilis)', abbreviations: ['RPR', 'VDRL'], synonyms: ['rpr', 'vdrl', 'syphilis test', 'syphilis screen', 'treponemal test'], category: 'Infectious Disease' },
  { name: 'Monospot Test', abbreviations: [], synonyms: ['monospot', 'mononucleosis', 'mono test', 'ebv screen', 'heterophile antibody'], category: 'Infectious Disease' },
  { name: 'Strep Throat Culture', abbreviations: [], synonyms: ['strep culture', 'throat culture', 'group a strep', 'rapid strep', 'streptococcal pharyngitis'], category: 'Infectious Disease' },
  { name: 'Urine Legionella Antigen', abbreviations: [], synonyms: ['legionella antigen', 'legionella urine', 'legionnaire disease test'], category: 'Infectious Disease' },
  { name: 'Urine Pneumococcal Antigen', abbreviations: [], synonyms: ['pneumococcal antigen', 'streptococcus pneumoniae antigen', 'pneumonia antigen test'], category: 'Infectious Disease' },
  { name: 'COVID-19 PCR', abbreviations: ['COVID PCR'], synonyms: ['covid pcr', 'sars-cov-2 pcr', 'coronavirus test', 'covid test', 'covid-19 test'], category: 'Infectious Disease' },
  { name: 'Influenza A/B PCR', abbreviations: [], synonyms: ['influenza pcr', 'flu test', 'influenza test', 'flu a b', 'rapid flu'], category: 'Infectious Disease' },
  { name: 'Tuberculin Skin Test (PPD)', abbreviations: ['PPD', 'TST'], synonyms: ['tuberculin skin test', 'ppd', 'mantoux test', 'tb skin test', 'tuberculosis test'], category: 'Infectious Disease' },
  { name: 'QuantiFERON-TB Gold', abbreviations: ['QFT'], synonyms: ['quantiferon', 'qft', 'igra', 'interferon gamma release', 'tb gold', 'latent tb test'], category: 'Infectious Disease' },

  // ── CARDIAC ──
  { name: 'Troponin I or T (high sensitivity)', abbreviations: ['Troponin', 'hsTnI', 'hsTnT'], synonyms: ['troponin', 'troponin i', 'troponin t', 'high sensitivity troponin', 'cardiac marker', 'heart attack marker', 'mi marker', 'acs marker'], category: 'Cardiac' },
  { name: 'BNP / NT-proBNP', abbreviations: ['BNP', 'NT-proBNP'], synonyms: ['bnp', 'nt-probnp', 'brain natriuretic peptide', 'heart failure marker', 'cardiac biomarker', 'chf marker'], category: 'Cardiac' },
  { name: 'CK-MB', abbreviations: ['CK-MB'], synonyms: ['ck-mb', 'creatine kinase mb', 'cardiac creatine kinase', 'myocardial infarction marker'], category: 'Cardiac' },
  { name: 'Myoglobin', abbreviations: [], synonyms: ['myoglobin', 'muscle damage marker', 'cardiac marker', 'rhabdomyolysis marker'], category: 'Cardiac' },
  { name: 'Digoxin Level', abbreviations: [], synonyms: ['digoxin level', 'digoxin', 'digitalis level', 'cardiac glycoside level'], category: 'Cardiac' },
  { name: 'Lipase / Amylase', abbreviations: [], synonyms: ['lipase', 'amylase', 'pancreatic enzymes', 'pancreatitis markers', 'pancreatic function'], category: 'Cardiac' },

  // ── TOXICOLOGY & DRUG LEVELS ──
  { name: 'Urine Drug Screen (UDS)', abbreviations: ['UDS'], synonyms: ['urine drug screen', 'uds', 'drug screen', 'toxicology screen', 'tox screen', 'substance screen'], category: 'Toxicology & Drug Levels' },
  { name: 'Blood Alcohol Level (BAL)', abbreviations: ['BAL', 'EtOH'], synonyms: ['blood alcohol', 'bal', 'etoh level', 'alcohol level', 'ethanol level'], category: 'Toxicology & Drug Levels' },
  { name: 'Acetaminophen Level', abbreviations: ['APAP'], synonyms: ['acetaminophen level', 'tylenol level', 'apap level', 'paracetamol level', 'overdose screen'], category: 'Toxicology & Drug Levels' },
  { name: 'Salicylate Level', abbreviations: [], synonyms: ['salicylate level', 'aspirin level', 'salicylism', 'asa level'], category: 'Toxicology & Drug Levels' },
  { name: 'Vancomycin Trough', abbreviations: [], synonyms: ['vancomycin trough', 'vancomycin level', 'vanc level', 'antibiotic level'], category: 'Toxicology & Drug Levels' },
  { name: 'Phenytoin Level', abbreviations: [], synonyms: ['phenytoin level', 'dilantin level', 'antiepileptic level', 'seizure medication level'], category: 'Toxicology & Drug Levels' },
  { name: 'Lithium Level', abbreviations: [], synonyms: ['lithium level', 'lithium toxicity', 'mood stabilizer level'], category: 'Toxicology & Drug Levels' },

  // ── ARTERIAL BLOOD GAS & RESPIRATORY ──
  { name: 'Arterial Blood Gas (ABG)', abbreviations: ['ABG'], synonyms: ['arterial blood gas', 'abg', 'blood gas', 'oxygen levels', 'acid base', 'ph pco2 po2', 'ventilation status'], category: 'ABG & Respiratory' },
  { name: 'Pulse Oximetry (SpO2)', abbreviations: ['SpO2', 'O2 sat'], synonyms: ['pulse oximetry', 'spo2', 'oxygen saturation', 'o2 sat', 'oxygen levels'], category: 'ABG & Respiratory' },
  { name: 'Peak Flow', abbreviations: ['PEFR'], synonyms: ['peak flow', 'peak expiratory flow', 'pefr', 'asthma monitoring'], category: 'ABG & Respiratory' },
  { name: 'Sputum Culture and Sensitivity', abbreviations: [], synonyms: ['sputum culture', 'sputum culture and sensitivity', 'respiratory culture', 'pneumonia culture'], category: 'ABG & Respiratory' },
  { name: 'Sputum Gram Stain', abbreviations: [], synonyms: ['sputum gram stain', 'gram stain', 'respiratory gram stain'], category: 'ABG & Respiratory' },

  // ── IMAGING ──
  { name: 'Chest X-Ray (PA and Lateral)', abbreviations: ['CXR', 'Chest XR'], synonyms: ['chest xray', 'chest x-ray', 'cxr', 'chest radiograph', 'pa lateral chest'], category: 'Imaging' },
  { name: 'CT Chest without Contrast', abbreviations: ['CT chest'], synonyms: ['ct chest', 'chest ct', 'ct thorax', 'lung ct', 'ct without contrast chest'], category: 'Imaging' },
  { name: 'CT Chest with Contrast', abbreviations: [], synonyms: ['ct chest with contrast', 'ct thorax with contrast', 'chest ct contrast'], category: 'Imaging' },
  { name: 'CT Abdomen and Pelvis without Contrast', abbreviations: ['CT A/P'], synonyms: ['ct abdomen pelvis', 'ct a/p', 'ct ap without contrast', 'ct belly', 'ct stomach'], category: 'Imaging' },
  { name: 'CT Abdomen and Pelvis with Contrast', abbreviations: [], synonyms: ['ct abdomen pelvis with contrast', 'ct ap with contrast', 'ct belly contrast'], category: 'Imaging' },
  { name: 'CT Head without Contrast', abbreviations: ['CT head', 'NCHCT'], synonyms: ['ct head', 'ct brain', 'head ct', 'brain ct', 'noncontrast head ct', 'stroke workup ct'], category: 'Imaging' },
  { name: 'MRI Brain with and without Contrast', abbreviations: ['MRI brain'], synonyms: ['mri brain', 'brain mri', 'mri head', 'head mri', 'mri with and without contrast brain'], category: 'Imaging' },
  { name: 'MRI Spine', abbreviations: [], synonyms: ['mri spine', 'spine mri', 'mri back', 'lumbar mri', 'cervical mri', 'thoracic mri', 'cord compression mri'], category: 'Imaging' },
  { name: 'Renal Ultrasound', abbreviations: [], synonyms: ['renal ultrasound', 'kidney ultrasound', 'kidney us', 'renal us', 'kidney sonogram'], category: 'Imaging' },
  { name: 'Abdominal Ultrasound', abbreviations: ['Abd US'], synonyms: ['abdominal ultrasound', 'abdominal us', 'belly ultrasound', 'right upper quadrant ultrasound', 'ruq ultrasound', 'liver gallbladder ultrasound'], category: 'Imaging' },
  { name: 'Pelvic Ultrasound', abbreviations: [], synonyms: ['pelvic ultrasound', 'pelvic us', 'ovarian ultrasound', 'uterine ultrasound', 'transvaginal ultrasound'], category: 'Imaging' },
  { name: 'Echocardiogram (Transthoracic)', abbreviations: ['TTE', 'Echo'], synonyms: ['echocardiogram', 'tte', 'transthoracic echo', 'echo', 'heart ultrasound', 'cardiac echo', 'cardiac ultrasound'], category: 'Imaging' },
  { name: 'Echocardiogram (Transesophageal)', abbreviations: ['TEE'], synonyms: ['transesophageal echo', 'tee', 'tee echo', 'endocarditis echo', 'detailed heart echo'], category: 'Imaging' },
  { name: 'Venous Doppler Ultrasound Bilateral Lower Extremities', abbreviations: ['LE Doppler', 'DVT US'], synonyms: ['dvt ultrasound', 'lower extremity doppler', 'le doppler', 'deep vein thrombosis ultrasound', 'venous duplex', 'leg ultrasound', 'dvt screen'], category: 'Imaging' },
  { name: 'V/Q Scan', abbreviations: ['VQ scan'], synonyms: ['vq scan', 'ventilation perfusion scan', 'lung scan', 'pulmonary embolism scan', 'vq'], category: 'Imaging' },
  { name: 'CT Pulmonary Angiography (CTPA)', abbreviations: ['CTPA', 'CTA chest'], synonyms: ['ctpa', 'ct pulmonary angiography', 'pe protocol', 'pe ct', 'pulmonary embolism ct', 'cta chest', 'pe workup'], category: 'Imaging' },
  { name: 'Bone Scan', abbreviations: [], synonyms: ['bone scan', 'nuclear bone scan', 'skeletal scintigraphy', 'metastatic bone scan'], category: 'Imaging' },
  { name: 'DEXA Scan', abbreviations: ['DXA'], synonyms: ['dexa scan', 'dxa scan', 'bone density', 'bone mineral density', 'osteoporosis scan'], category: 'Imaging' },

  // ── PROCEDURES & SPECIAL TESTS ──
  { name: 'Electrocardiogram (ECG/EKG)', abbreviations: ['ECG', 'EKG'], synonyms: ['electrocardiogram', 'ecg', 'ekg', 'heart tracing', 'cardiac rhythm', '12-lead ecg', 'heart rhythm'], category: 'Procedures & Special Tests' },
  { name: 'Holter Monitor (24-hour)', abbreviations: ['Holter'], synonyms: ['holter monitor', 'ambulatory ecg', '24-hour ecg', 'continuous heart monitor', 'arrhythmia monitor'], category: 'Procedures & Special Tests' },
  { name: 'Stress Test (Exercise Treadmill)', abbreviations: ['ETT'], synonyms: ['stress test', 'exercise treadmill test', 'ett', 'exercise ecg', 'cardiac stress test', 'nuclear stress test'], category: 'Procedures & Special Tests' },
  { name: 'Lumbar Puncture (CSF Analysis)', abbreviations: ['LP', 'CSF'], synonyms: ['lumbar puncture', 'lp', 'spinal tap', 'csf analysis', 'cerebrospinal fluid', 'csf', 'meningitis workup'], category: 'Procedures & Special Tests' },
  { name: 'Bone Marrow Biopsy', abbreviations: ['BMBx'], synonyms: ['bone marrow biopsy', 'bone marrow aspirate', 'bm biopsy', 'hematology biopsy', 'leukemia workup'], category: 'Procedures & Special Tests' },
  { name: 'Skin Biopsy', abbreviations: [], synonyms: ['skin biopsy', 'dermatology biopsy', 'punch biopsy', 'skin lesion biopsy'], category: 'Procedures & Special Tests' },
  { name: 'Renal Biopsy', abbreviations: [], synonyms: ['renal biopsy', 'kidney biopsy', 'nephrology biopsy', 'glomerulonephritis biopsy'], category: 'Procedures & Special Tests' },
  { name: 'Liver Biopsy', abbreviations: [], synonyms: ['liver biopsy', 'hepatic biopsy', 'hepatology biopsy', 'liver tissue'], category: 'Procedures & Special Tests' },
  { name: 'Colonoscopy', abbreviations: [], synonyms: ['colonoscopy', 'colon scope', 'lower gi endoscopy', 'colorectal screen', 'colon cancer screen'], category: 'Procedures & Special Tests' },
  { name: 'Upper Endoscopy (EGD)', abbreviations: ['EGD'], synonyms: ['upper endoscopy', 'egd', 'esophagogastroduodenoscopy', 'gastroscopy', 'upper gi scope', 'stomach scope'], category: 'Procedures & Special Tests' },
  { name: 'Bronchoscopy', abbreviations: [], synonyms: ['bronchoscopy', 'lung biopsy', 'airway scope', 'respiratory procedure', 'bal bronchoscopy'], category: 'Procedures & Special Tests' },
  { name: 'Spirometry / PFTs', abbreviations: ['PFTs'], synonyms: ['spirometry', 'pulmonary function tests', 'pfts', 'lung function', 'fev1 fvc', 'airway obstruction test', 'asthma test', 'copd evaluation'], category: 'Procedures & Special Tests' },
  { name: 'Nerve Conduction Study (NCS)', abbreviations: ['NCS'], synonyms: ['nerve conduction study', 'ncs', 'nerve conduction', 'peripheral neuropathy test', 'electrophysiology'], category: 'Procedures & Special Tests' },
  { name: 'EMG', abbreviations: ['EMG'], synonyms: ['emg', 'electromyography', 'muscle electrophysiology', 'neuromuscular test', 'motor unit testing'], category: 'Procedures & Special Tests' },

  // ── ADVANCED-ONLY ──
  { name: 'Anti-Phospholipid Antibodies (aCL, anti-β2GP1, LA)', abbreviations: ['APS panel', 'aPL'], synonyms: ['antiphospholipid antibodies', 'acl antibody', 'beta2 glycoprotein', 'lupus anticoagulant', 'aps panel', 'antiphospholipid syndrome'], category: 'Advanced Immunology' },
  { name: 'Anti-Histone Antibody', abbreviations: [], synonyms: ['anti histone', 'drug induced lupus antibody', 'histone antibody'], category: 'Advanced Immunology' },
  { name: 'Anti-Ro (SSA) / Anti-La (SSB)', abbreviations: ['SSA', 'SSB'], synonyms: ['anti-ro ssa', 'anti-la ssb', 'sjogren antibody', 'sjögren antibody', 'ssa ssb', 'neonatal lupus antibody'], category: 'Advanced Immunology' },
  { name: 'Anti-Scl-70 / Anti-Centromere', abbreviations: ['Scl-70'], synonyms: ['anti scl-70', 'anti centromere', 'scleroderma antibody', 'systemic sclerosis antibody', 'crest antibody'], category: 'Advanced Immunology' },
  { name: 'Anti-Jo-1', abbreviations: ['Jo-1'], synonyms: ['anti jo-1', 'antisynthetase antibody', 'myositis antibody', 'inflammatory myopathy antibody'], category: 'Advanced Immunology' },
  { name: 'Serum Free Light Chains (Kappa/Lambda)', abbreviations: ['FLC'], synonyms: ['serum free light chains', 'kappa lambda', 'flc', 'myeloma marker', 'plasma cell disorder'], category: 'Advanced Hematology' },
  { name: 'Beta-2 Microglobulin', abbreviations: ['B2M'], synonyms: ['beta-2 microglobulin', 'b2m', 'b2 microglobulin', 'myeloma marker', 'lymphoma staging'], category: 'Advanced Hematology' },
  { name: 'Coombs Test (Direct / Indirect)', abbreviations: ['DAT', 'IAT'], synonyms: ['coombs test', 'direct antiglobulin', 'indirect antiglobulin', 'dat', 'iat', 'autoimmune hemolysis', 'hemolytic anemia workup'], category: 'Advanced Hematology' },
  { name: 'Haptoglobin', abbreviations: [], synonyms: ['haptoglobin', 'hemolysis marker', 'intravascular hemolysis'], category: 'Advanced Hematology' },
  { name: 'Osmolality (Serum and Urine)', abbreviations: [], synonyms: ['osmolality', 'serum osmolality', 'urine osmolality', 'osmol gap', 'hyponatremia workup', 'siadh workup'], category: 'Advanced Chemistry' },
  { name: 'Spot Urine Osmolality', abbreviations: [], synonyms: ['urine osmolality', 'spot urine osmolality', 'urine concentration', 'siadh workup', 'diabetes insipidus workup'], category: 'Advanced Chemistry' },
  { name: 'Urine Eosinophils', abbreviations: [], synonyms: ['urine eosinophils', 'eosinophiluria', 'acute interstitial nephritis workup', 'ain workup'], category: 'Advanced Renal' },
  { name: 'Anti-PLA2R Antibody', abbreviations: ['PLA2R'], synonyms: ['anti pla2r', 'membranous nephropathy antibody', 'pla2r antibody', 'membranous glomerulopathy'], category: 'Advanced Renal' },
  { name: 'SPEP with Immunofixation', abbreviations: ['SPEP IFE'], synonyms: ['spep immunofixation', 'serum protein electrophoresis immunofixation', 'ife', 'm-protein', 'myeloma confirmation', 'immunofixation electrophoresis'], category: 'Advanced Chemistry' },
  { name: 'Free Kappa/Lambda Light Chain Ratio', abbreviations: [], synonyms: ['kappa lambda ratio', 'free light chain ratio', 'myeloma ratio', 'plasma cell dyscrasia'], category: 'Advanced Hematology' },
  { name: 'Renin / Aldosterone Ratio', abbreviations: ['ARR'], synonyms: ['renin aldosterone ratio', 'arr', 'hyperaldosteronism workup', 'primary aldosteronism', 'hypertension workup'], category: 'Advanced Endocrine' },
  { name: '24-Hour Urine Cortisol', abbreviations: [], synonyms: ['urine cortisol', '24 hour cortisol', 'cushing workup', 'hypercortisolism'], category: 'Advanced Endocrine' },
  { name: 'ACTH Stimulation Test', abbreviations: ['cosyntropin test'], synonyms: ['acth stimulation', 'cosyntropin stimulation', 'cortrosyn test', 'adrenal insufficiency test', 'addison workup'], category: 'Advanced Endocrine' },
  { name: 'Dexamethasone Suppression Test', abbreviations: ['DST'], synonyms: ['dexamethasone suppression', 'dst', 'cushing workup', 'cortisol suppression'], category: 'Advanced Endocrine' },
  { name: 'Thyroid Peroxidase Antibody (TPO Ab)', abbreviations: ['TPO Ab', 'Anti-TPO'], synonyms: ['thyroid peroxidase antibody', 'tpo ab', 'anti-tpo', 'hashimoto antibody', 'autoimmune thyroid'], category: 'Advanced Endocrine' },
  { name: 'Thyroglobulin Antibody', abbreviations: ['TgAb'], synonyms: ['thyroglobulin antibody', 'tgab', 'anti-thyroglobulin', 'thyroid cancer marker'], category: 'Advanced Endocrine' },
  { name: 'Parathyroid Hormone (PTH)', abbreviations: ['PTH'], synonyms: ['parathyroid hormone', 'pth', 'calcium regulation', 'hypercalcemia workup', 'hyperparathyroidism'], category: 'Advanced Endocrine' },
  { name: '25-OH Vitamin D', abbreviations: ['Vit D'], synonyms: ['vitamin d', '25-oh vitamin d', 'cholecalciferol', 'vitamin d deficiency', 'vit d level'], category: 'Advanced Endocrine' },
  { name: '1,25-OH Vitamin D', abbreviations: [], synonyms: ['1,25 vitamin d', 'calcitriol', 'active vitamin d', 'granulomatous disease calcium'], category: 'Advanced Endocrine' },
  { name: 'Serum Protein C / Protein S', abbreviations: [], synonyms: ['protein c', 'protein s', 'thrombophilia', 'hypercoagulable workup', 'clotting disorder'], category: 'Advanced Coagulation' },
  { name: 'Factor V Leiden', abbreviations: [], synonyms: ['factor v leiden', 'activated protein c resistance', 'thrombophilia', 'hypercoagulable workup', 'dvt genetics'], category: 'Advanced Coagulation' },
  { name: 'Prothrombin Gene Mutation', abbreviations: ['Factor II'], synonyms: ['prothrombin gene mutation', 'factor ii mutation', 'g20210a', 'thrombophilia genetic test'], category: 'Advanced Coagulation' },
  { name: 'Antithrombin III', abbreviations: ['AT III', 'AT3'], synonyms: ['antithrombin', 'antithrombin iii', 'at3', 'hypercoagulable workup', 'thrombophilia'], category: 'Advanced Coagulation' },
  { name: 'Mixing Study', abbreviations: [], synonyms: ['mixing study', 'factor inhibitor screen', 'coagulation mixing study', 'lupus anticoagulant workup'], category: 'Advanced Coagulation' },
  { name: 'Thromboelastography (TEG)', abbreviations: ['TEG', 'ROTEM'], synonyms: ['thromboelastography', 'teg', 'rotem', 'viscoelastic coagulation', 'clot formation testing'], category: 'Advanced Coagulation' },
  { name: 'Cryptococcal Antigen', abbreviations: ['CrAg'], synonyms: ['cryptococcal antigen', 'crag', 'cryptococcus antigen', 'fungal meningitis', 'hiv meningitis screen'], category: 'Advanced Infectious Disease' },
  { name: 'Histoplasma Urine Antigen', abbreviations: [], synonyms: ['histoplasma antigen', 'histoplasmosis test', 'histoplasma urine', 'endemic fungal infection'], category: 'Advanced Infectious Disease' },
  { name: 'Aspergillus Galactomannan', abbreviations: ['GM'], synonyms: ['galactomannan', 'aspergillus antigen', 'aspergillosis marker', 'fungal biomarker'], category: 'Advanced Infectious Disease' },
  { name: 'Beta-D-Glucan', abbreviations: ['BDG'], synonyms: ['beta d glucan', 'bdg', 'fungal biomarker', 'fungemia screen', 'candida aspergillus screen'], category: 'Advanced Infectious Disease' },
  { name: 'EBV VCA IgM/IgG', abbreviations: ['EBV'], synonyms: ['ebv antibody', 'epstein barr', 'ebv vca', 'ebv serology', 'mononucleosis serology'], category: 'Advanced Infectious Disease' },
  { name: 'CMV IgM/IgG', abbreviations: ['CMV'], synonyms: ['cmv antibody', 'cytomegalovirus', 'cmv serology', 'cmv igm igg'], category: 'Advanced Infectious Disease' },
  { name: 'Parvovirus B19 IgM/IgG', abbreviations: [], synonyms: ['parvovirus b19', 'fifth disease antibody', 'parvovirus antibody', 'aplastic crisis workup'], category: 'Advanced Infectious Disease' },
  { name: 'Lyme Disease Antibody (ELISA + Western Blot)', abbreviations: ['Lyme Ab'], synonyms: ['lyme disease', 'lyme antibody', 'borrelia antibody', 'lyme elisa western blot', 'tick borne illness'], category: 'Advanced Infectious Disease' },
  { name: 'Rocky Mountain Spotted Fever (RMSF) Antibody', abbreviations: ['RMSF'], synonyms: ['rocky mountain spotted fever', 'rmsf', 'rickettsia antibody', 'tick borne rickettsial disease'], category: 'Advanced Infectious Disease' },
  { name: 'Ehrlichia / Anaplasmosis Panel', abbreviations: [], synonyms: ['ehrlichia', 'anaplasmosis', 'tick borne illness panel', 'ehrlichiosis antibody'], category: 'Advanced Infectious Disease' },
  { name: 'Babesia Blood Smear', abbreviations: [], synonyms: ['babesia smear', 'babesiosis', 'tick borne parasite', 'intraerythrocytic parasite'], category: 'Advanced Infectious Disease' },
  { name: 'Malaria Blood Smear / RDT', abbreviations: [], synonyms: ['malaria smear', 'malaria rdt', 'malaria test', 'plasmodium', 'travel fever workup'], category: 'Advanced Infectious Disease' },
  { name: 'Stool Culture', abbreviations: [], synonyms: ['stool culture', 'fecal culture', 'gi culture', 'diarrhea workup', 'gastroenteritis culture'], category: 'Advanced GI' },
  { name: 'Stool Ova and Parasites', abbreviations: ['O&P'], synonyms: ['ova and parasites', 'o and p', 'stool parasites', 'parasite stool', 'diarrhea workup'], category: 'Advanced GI' },
  { name: 'Stool C. difficile PCR', abbreviations: ['C diff PCR'], synonyms: ['c diff', 'c. difficile', 'clostridioides difficile', 'c diff pcr', 'cdiff toxin', 'antibiotic associated diarrhea'], category: 'Advanced GI' },
  { name: 'Fecal Calprotectin', abbreviations: [], synonyms: ['fecal calprotectin', 'stool calprotectin', 'ibd marker', 'intestinal inflammation marker', 'crohn colitis marker'], category: 'Advanced GI' },
  { name: 'Fecal Occult Blood Test (FOBT)', abbreviations: ['FOBT', 'FIT'], synonyms: ['fecal occult blood', 'fobt', 'fit test', 'guaiac test', 'stool blood test', 'colorectal screen'], category: 'Advanced GI' },
  { name: 'Fecal Elastase', abbreviations: [], synonyms: ['fecal elastase', 'stool elastase', 'exocrine pancreatic insufficiency', 'pancreatic function test'], category: 'Advanced GI' },
  { name: 'Sweat Chloride Test', abbreviations: [], synonyms: ['sweat chloride', 'cystic fibrosis test', 'cf sweat test', 'pilocarpine iontophoresis'], category: 'Advanced Pulmonary' },
  { name: 'Alpha-1 Antitrypsin Level', abbreviations: ['A1AT', 'AAT'], synonyms: ['alpha-1 antitrypsin', 'a1at', 'aat', 'emphysema workup', 'alpha1 protease inhibitor'], category: 'Advanced Pulmonary' },
  { name: 'Ceruloplasmin / Serum Copper', abbreviations: [], synonyms: ['ceruloplasmin', 'serum copper', 'wilson disease workup', 'copper metabolism'], category: 'Advanced Metabolic' },
  { name: 'Serum Ammonia', abbreviations: [], synonyms: ['serum ammonia', 'ammonia level', 'hepatic encephalopathy', 'liver failure marker'], category: 'Advanced Metabolic' },
  { name: 'Lactate (Serum)', abbreviations: ['Lactate'], synonyms: ['serum lactate', 'lactic acid', 'lactate level', 'sepsis marker', 'tissue hypoxia', 'shock marker'], category: 'Advanced Metabolic' },
  { name: 'Pyruvate', abbreviations: [], synonyms: ['pyruvate', 'mitochondrial disease', 'lactate pyruvate ratio'], category: 'Advanced Metabolic' },
  { name: 'Acylcarnitine Profile', abbreviations: [], synonyms: ['acylcarnitine', 'fatty acid oxidation disorder', 'metabolic disease screen'], category: 'Advanced Metabolic' },
  { name: 'Amino Acid Profile', abbreviations: [], synonyms: ['amino acids', 'plasma amino acids', 'aminoacidopathy', 'metabolic screen'], category: 'Advanced Metabolic' },
  { name: 'Urine Organic Acids', abbreviations: [], synonyms: ['urine organic acids', 'organic aciduria', 'metabolic disease workup'], category: 'Advanced Metabolic' },
  { name: 'Lead Level', abbreviations: [], synonyms: ['lead level', 'blood lead', 'lead poisoning', 'heavy metal toxicity'], category: 'Advanced Toxicology' },
  { name: 'Mercury Level', abbreviations: [], synonyms: ['mercury level', 'blood mercury', 'mercury poisoning', 'heavy metal toxicity'], category: 'Advanced Toxicology' },
  { name: 'Arsenic Level', abbreviations: [], synonyms: ['arsenic level', 'arsenic poisoning', 'heavy metal toxicity'], category: 'Advanced Toxicology' },
  { name: 'Carboxyhemoglobin', abbreviations: ['COHb'], synonyms: ['carboxyhemoglobin', 'cohb', 'carbon monoxide poisoning', 'co poisoning', 'smoke inhalation'], category: 'Advanced Toxicology' },
  { name: 'Methemoglobin', abbreviations: ['MetHb'], synonyms: ['methemoglobin', 'methb', 'methemoglobinemia', 'cyanosis workup', 'dapsone toxicity'], category: 'Advanced Toxicology' },
  { name: 'Cholinesterase (RBC and Plasma)', abbreviations: [], synonyms: ['cholinesterase', 'organophosphate poisoning', 'nerve agent exposure', 'rbc cholinesterase'], category: 'Advanced Toxicology' },
  { name: 'Tryptase (Serum)', abbreviations: [], synonyms: ['serum tryptase', 'mast cell tryptase', 'anaphylaxis marker', 'mastocytosis marker'], category: 'Advanced Immunology' },
  { name: 'IgE (Total and Specific Allergen)', abbreviations: ['IgE'], synonyms: ['total ige', 'specific ige', 'allergy test', 'atopy', 'allergic disease'], category: 'Advanced Immunology' },
  { name: 'RAST Panel', abbreviations: ['RAST'], synonyms: ['rast test', 'radioallergosorbent test', 'specific ige panel', 'allergy panel'], category: 'Advanced Immunology' },
  { name: 'Flow Cytometry (Peripheral Blood)', abbreviations: [], synonyms: ['flow cytometry', 'peripheral blood flow', 'lymphocyte subset', 'cd4 count', 'immunophenotyping', 'hematologic malignancy'], category: 'Advanced Hematology' },
  { name: 'JAK2 V617F Mutation', abbreviations: ['JAK2'], synonyms: ['jak2 mutation', 'jak2 v617f', 'myeloproliferative neoplasm', 'polycythemia vera workup', 'essential thrombocythemia workup'], category: 'Advanced Hematology' },
  { name: 'BCR-ABL PCR', abbreviations: ['BCR-ABL'], synonyms: ['bcr-abl', 'philadelphia chromosome pcr', 'cml marker', 'chronic myeloid leukemia marker'], category: 'Advanced Hematology' },
  { name: 'FISH Panel', abbreviations: ['FISH'], synonyms: ['fish', 'fluorescence in situ hybridization', 'chromosomal translocation', 'lymphoma genetics', 'leukemia genetics'], category: 'Advanced Genetics' },
  { name: 'Karyotype', abbreviations: [], synonyms: ['karyotype', 'chromosomal analysis', 'cytogenetics', 'chromosomal abnormality'], category: 'Advanced Genetics' },
  { name: 'Microarray (Chromosomal)', abbreviations: [], synonyms: ['chromosomal microarray', 'snp array', 'copy number variant', 'chromosomal deletion duplication'], category: 'Advanced Genetics' },
  { name: 'BRCA1/BRCA2', abbreviations: ['BRCA'], synonyms: ['brca testing', 'brca1 brca2', 'hereditary breast ovarian cancer', 'genetic cancer risk'], category: 'Advanced Genetics' },
  { name: 'Lynch Syndrome Panel', abbreviations: [], synonyms: ['lynch syndrome', 'hereditary colorectal cancer', 'mismatch repair genes', 'msh2 mlh1'], category: 'Advanced Genetics' },
  { name: 'PSA (Prostate Specific Antigen)', abbreviations: ['PSA'], synonyms: ['psa', 'prostate antigen', 'prostate cancer screen', 'prostate specific antigen'], category: 'Advanced Oncology' },
  { name: 'CA-125', abbreviations: ['CA-125'], synonyms: ['ca 125', 'ca-125', 'ovarian cancer marker', 'peritoneal cancer marker'], category: 'Advanced Oncology' },
  { name: 'CA 19-9', abbreviations: ['CA 19-9'], synonyms: ['ca 19-9', 'pancreatic cancer marker', 'biliary cancer marker'], category: 'Advanced Oncology' },
  { name: 'CEA (Carcinoembryonic Antigen)', abbreviations: ['CEA'], synonyms: ['cea', 'carcinoembryonic antigen', 'colorectal cancer marker', 'tumor marker'], category: 'Advanced Oncology' },
  { name: 'AFP (Alpha-Fetoprotein)', abbreviations: ['AFP'], synonyms: ['afp', 'alpha-fetoprotein', 'liver cancer marker', 'hepatocellular carcinoma marker', 'germ cell tumor marker'], category: 'Advanced Oncology' },
  { name: 'Beta-hCG (Quantitative)', abbreviations: ['hCG', 'Beta-hCG'], synonyms: ['beta hcg', 'quantitative hcg', 'pregnancy test', 'gestational trophoblastic disease', 'germ cell tumor marker'], category: 'Advanced Oncology' },
  { name: 'Testosterone (Total and Free)', abbreviations: [], synonyms: ['testosterone', 'total testosterone', 'free testosterone', 'androgen level', 'hypogonadism workup'], category: 'Advanced Endocrine' },
  { name: 'LH / FSH', abbreviations: ['LH', 'FSH'], synonyms: ['lh fsh', 'luteinizing hormone', 'follicle stimulating hormone', 'gonadotropins', 'hypogonadism workup', 'infertility workup'], category: 'Advanced Endocrine' },
  { name: 'Prolactin', abbreviations: [], synonyms: ['prolactin', 'prolactinoma', 'hyperprolactinemia', 'pituitary workup'], category: 'Advanced Endocrine' },
  { name: 'Estradiol', abbreviations: ['E2'], synonyms: ['estradiol', 'e2', 'estrogen level', 'menopause workup', 'ovarian function'], category: 'Advanced Endocrine' },
  { name: 'Progesterone', abbreviations: [], synonyms: ['progesterone', 'luteal phase', 'ovulation confirmation'], category: 'Advanced Endocrine' },
  { name: 'DHEA-S', abbreviations: ['DHEA-S', 'DHEAS'], synonyms: ['dhea-s', 'dehydroepiandrosterone sulfate', 'adrenal androgen', 'hirsutism workup'], category: 'Advanced Endocrine' },
  { name: 'IGF-1', abbreviations: ['IGF-1'], synonyms: ['igf-1', 'insulin-like growth factor', 'growth hormone deficiency', 'acromegaly marker'], category: 'Advanced Endocrine' },
  { name: 'Growth Hormone Stimulation Test', abbreviations: [], synonyms: ['growth hormone stimulation', 'gh stimulation', 'growth hormone deficiency', 'pituitary function test'], category: 'Advanced Endocrine' },
  { name: 'Insulin Level (Fasting)', abbreviations: [], synonyms: ['fasting insulin', 'insulin level', 'insulin resistance', 'homa-ir', 'hyperinsulinemia'], category: 'Advanced Endocrine' },
  { name: 'C-Peptide', abbreviations: [], synonyms: ['c-peptide', 'c peptide', 'insulin secretion', 'type 1 vs type 2 diabetes'], category: 'Advanced Endocrine' },
  { name: 'Zinc / Selenium / Copper', abbreviations: [], synonyms: ['zinc level', 'selenium level', 'copper level', 'micronutrient', 'trace element', 'nutritional deficiency'], category: 'Advanced Metabolic' },
  { name: 'PET Scan', abbreviations: ['PET'], synonyms: ['pet scan', 'positron emission tomography', 'fdg pet', 'cancer staging', 'metabolic imaging'], category: 'Advanced Imaging' },
  { name: 'MIBG Scan', abbreviations: ['MIBG'], synonyms: ['mibg scan', 'metaiodobenzylguanidine', 'pheochromocytoma scan', 'neuroblastoma scan'], category: 'Advanced Imaging' },
  { name: 'Gallium Scan', abbreviations: [], synonyms: ['gallium scan', 'gallium-67', 'lymphoma staging', 'infection imaging'], category: 'Advanced Imaging' },
  { name: 'Tagged RBC Scan', abbreviations: ['tagged RBC'], synonyms: ['tagged rbc scan', 'red blood cell scan', 'gi bleeding localization', 'nuclear gi bleed'], category: 'Advanced Imaging' },
  { name: 'Gastric Emptying Study', abbreviations: [], synonyms: ['gastric emptying study', 'gastroparesis test', 'gastric motility', 'nuclear gastric emptying'], category: 'Advanced Imaging' },
  { name: 'Capsule Endoscopy', abbreviations: [], synonyms: ['capsule endoscopy', 'video capsule', 'small bowel capsule', 'obscure gi bleed', 'small bowel imaging'], category: 'Advanced Procedures' },
  { name: 'Push Enteroscopy', abbreviations: [], synonyms: ['push enteroscopy', 'small bowel enteroscopy', 'jejunum scope'], category: 'Advanced Procedures' },
  { name: 'ERCP', abbreviations: ['ERCP'], synonyms: ['ercp', 'endoscopic retrograde cholangiopancreatography', 'biliary procedure', 'pancreatic duct', 'gallstone removal'], category: 'Advanced Procedures' },
  { name: 'Endoscopic Ultrasound (EUS)', abbreviations: ['EUS'], synonyms: ['endoscopic ultrasound', 'eus', 'pancreatic mass biopsy', 'biliary staging'], category: 'Advanced Procedures' },
  { name: 'Cystoscopy', abbreviations: [], synonyms: ['cystoscopy', 'bladder scope', 'urologic procedure', 'hematuria workup'], category: 'Advanced Procedures' },
  { name: 'Urodynamic Studies', abbreviations: [], synonyms: ['urodynamics', 'bladder function testing', 'incontinence workup', 'voiding dysfunction'], category: 'Advanced Procedures' },
  { name: 'Cardiac Catheterization', abbreviations: ['Cath'], synonyms: ['cardiac catheterization', 'coronary angiogram', 'left heart cath', 'cath lab', 'coronary artery disease workup'], category: 'Advanced Cardiac' },
  { name: 'Coronary CT Angiography (CCTA)', abbreviations: ['CCTA', 'CTA coronary'], synonyms: ['ccta', 'coronary cta', 'ct coronary angiography', 'calcium scoring ct', 'coronary artery disease noninvasive'], category: 'Advanced Cardiac' },
  { name: 'Ankle-Brachial Index (ABI)', abbreviations: ['ABI'], synonyms: ['ankle brachial index', 'abi', 'peripheral arterial disease', 'pad screen'], category: 'Advanced Vascular' },
  { name: 'Carotid Doppler Ultrasound', abbreviations: [], synonyms: ['carotid doppler', 'carotid ultrasound', 'carotid duplex', 'stroke workup', 'tia workup', 'carotid stenosis'], category: 'Advanced Vascular' },
  { name: 'Tilt Table Test', abbreviations: [], synonyms: ['tilt table test', 'orthostatic hypotension test', 'syncope workup', 'autonomic testing'], category: 'Advanced Cardiac' },
  { name: 'Electroencephalogram (EEG)', abbreviations: ['EEG'], synonyms: ['eeg', 'electroencephalogram', 'seizure workup', 'brain waves', 'epilepsy monitoring'], category: 'Advanced Neurology' },
  { name: 'Evoked Potentials (VEP, SSEP, BAER)', abbreviations: ['VEP', 'SSEP', 'BAER'], synonyms: ['evoked potentials', 'vep', 'ssep', 'baer', 'visual evoked potential', 'somatosensory evoked', 'brainstem auditory evoked', 'ms workup', 'demyelination'], category: 'Advanced Neurology' },
  { name: 'Polysomnography (Sleep Study)', abbreviations: ['PSG'], synonyms: ['polysomnography', 'sleep study', 'psg', 'sleep apnea test', 'overnight sleep study', 'obstructive sleep apnea'], category: 'Advanced Pulmonary' },
  { name: 'Skin Prick Test', abbreviations: [], synonyms: ['skin prick test', 'allergy skin test', 'epicutaneous test', 'hypersensitivity testing'], category: 'Advanced Immunology' },
  { name: 'Patch Test', abbreviations: [], synonyms: ['patch test', 'contact dermatitis test', 'allergic contact', 'delayed hypersensitivity test'], category: 'Advanced Immunology' },
  { name: 'Pulmonary Artery Catheterization (Swan-Ganz)', abbreviations: ['PA cath', 'Swan-Ganz'], synonyms: ['swan ganz', 'pulmonary artery catheter', 'pa catheter', 'hemodynamic monitoring', 'right heart pressures'], category: 'Advanced Cardiac' },
  { name: 'Right Heart Catheterization', abbreviations: ['RHC'], synonyms: ['right heart cath', 'rhc', 'right heart catheterization', 'pulmonary hypertension workup', 'hemodynamic assessment'], category: 'Advanced Cardiac' },
  { name: 'Pericardiocentesis', abbreviations: [], synonyms: ['pericardiocentesis', 'pericardial drain', 'pericardial effusion drainage', 'tamponade treatment'], category: 'Advanced Procedures' },
  { name: 'Thoracentesis (with fluid analysis)', abbreviations: [], synonyms: ['thoracentesis', 'pleural tap', 'pleural fluid analysis', 'pleural effusion drainage', 'light criteria'], category: 'Advanced Procedures' },
  { name: 'Paracentesis (with fluid analysis)', abbreviations: [], synonyms: ['paracentesis', 'ascites tap', 'peritoneal fluid analysis', 'ascites drainage', 'saag'], category: 'Advanced Procedures' },
  { name: 'Arthrocentesis (with synovial fluid analysis)', abbreviations: [], synonyms: ['arthrocentesis', 'joint aspiration', 'synovial fluid', 'joint tap', 'gout workup', 'septic arthritis workup', 'crystal arthropathy'], category: 'Advanced Procedures' },
  { name: 'Skin Scraping / KOH Prep', abbreviations: ['KOH'], synonyms: ['koh prep', 'skin scraping', 'koh test', 'fungal skin test', 'dermatophyte test', 'tinea test'], category: 'Advanced Procedures' },
  { name: 'Tzanck Smear', abbreviations: [], synonyms: ['tzanck smear', 'tzanck test', 'herpes smear', 'vesicular rash workup'], category: 'Advanced Procedures' },
  { name: "Wood's Lamp Examination", abbreviations: ["Wood's lamp"], synonyms: ["wood's lamp", 'woodslamp', 'uv light skin exam', 'fluorescence skin exam', 'tinea capitis screen'], category: 'Advanced Procedures' },
]

export function searchTests(query: string, list: TestEntry[] = MASTER_TEST_LIST): TestEntry[] {
  const words = query.toLowerCase().trim().split(/\s+/).filter(Boolean)
  if (!words.length) return []
  return list.filter(t => {
    const haystack = [t.name, ...t.abbreviations, ...t.synonyms].join(' ').toLowerCase()
    return words.every(w => haystack.includes(w))
  }).slice(0, 12)
}
