-- ─────────────────────────────────────────────────────────────────────────────
-- MedTrainer — Supabase Schema
-- Run this once in the Supabase SQL Editor (Database → SQL Editor → New query)
-- ─────────────────────────────────────────────────────────────────────────────

-- ── Migration: add imaging_cache columns (run if table already exists) ────────
ALTER TABLE cases ADD COLUMN IF NOT EXISTS imaging_cache     JSONB       NOT NULL DEFAULT '{}';
ALTER TABLE cases ADD COLUMN IF NOT EXISTS imaging_cached_at TIMESTAMPTZ;

-- ── Migration: drop unused cases.patient_name (jitterCase randomises name per session) ──
ALTER TABLE cases DROP COLUMN IF EXISTS patient_name;

-- ── Migration: Phase 4 — bookmark flag + redo lineage on case_sessions ────────
ALTER TABLE case_sessions ADD COLUMN IF NOT EXISTS bookmarked        BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE case_sessions ADD COLUMN IF NOT EXISTS parent_session_id TEXT    REFERENCES case_sessions(id) ON DELETE SET NULL;
-- ─────────────────────────────────────────────────────────────────────────────

-- ── Cases library ─────────────────────────────────────────────────────────────
-- Stores the 432 case slots (system × difficulty × diagnosis × variant).
-- case_data is null until a case is first generated by Claude, then cached.

CREATE TABLE IF NOT EXISTS cases (
  id                TEXT        PRIMARY KEY,
  system            TEXT        NOT NULL,
  difficulty        TEXT        NOT NULL,
  diagnosis         TEXT        NOT NULL,
  variant_index     INT         NOT NULL DEFAULT 0,
  case_data         JSONB,
  is_generated      BOOLEAN     NOT NULL DEFAULT FALSE,
  generated_at      TIMESTAMPTZ,
  -- Pre-fetched Open-i image results keyed by imaging test name.
  -- Structure: { "Chest X-Ray": [{uid, imageUrl, thumbnailUrl, caption, modality}], ... }
  -- Empty array = tried + found nothing (needs manual curation).
  -- Missing key = not yet prefetched (trainer will fetch live).
  imaging_cache     JSONB       NOT NULL DEFAULT '{}',
  imaging_cached_at TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Run this in the SQL editor if the table already exists:
-- ALTER TABLE cases ADD COLUMN IF NOT EXISTS imaging_cache JSONB NOT NULL DEFAULT '{}';
-- ALTER TABLE cases ADD COLUMN IF NOT EXISTS imaging_cached_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS cases_system_difficulty ON cases (system, difficulty);
CREATE INDEX IF NOT EXISTS cases_is_generated      ON cases (is_generated);

-- ── User profiles ─────────────────────────────────────────────────────────────
-- Extends auth.users. Auto-created by trigger on signup.

CREATE TABLE IF NOT EXISTS profiles (
  id                    UUID        PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  display_name          TEXT,
  role                  TEXT        NOT NULL DEFAULT 'student'
                                    CHECK (role IN ('student', 'admin')),
  -- freemium fields
  tier                  TEXT        NOT NULL DEFAULT 'free'
                                    CHECK (tier IN ('free', 'pro')),
  cases_used_today      INT         NOT NULL DEFAULT 0,
  cases_today_reset_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  first_case_completed  BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Automatically create a profile row when a new user signs up
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO profiles (id, display_name, tier, cases_used_today, cases_today_reset_at, first_case_completed)
  VALUES (NEW.id, SPLIT_PART(NEW.email, '@', 1), 'free', 0, NOW(), FALSE)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- ── Case sessions ─────────────────────────────────────────────────────────────
-- One row per completed case, linked to the user.

CREATE TABLE IF NOT EXISTS case_sessions (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID        NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  case_id       TEXT,
  system        TEXT        NOT NULL,
  difficulty    TEXT        NOT NULL,
  diagnosis     TEXT        NOT NULL,
  score         INT         NOT NULL,
  correct       BOOLEAN     NOT NULL,
  grading_data  JSONB,
  completed_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS sessions_user_id     ON case_sessions (user_id);
CREATE INDEX IF NOT EXISTS sessions_completed   ON case_sessions (completed_at DESC);

-- ── Ratings ───────────────────────────────────────────────────────────────────
-- One row per submitted feedback widget. user_id is NULL for anonymous users.

CREATE TABLE IF NOT EXISTS ratings (
  id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id               UUID        REFERENCES auth.users (id) ON DELETE SET NULL,
  case_id               TEXT        REFERENCES cases (id)      ON DELETE SET NULL,
  -- denormalized for easy querying without joins
  diagnosis             TEXT        NOT NULL,
  system                TEXT        NOT NULL,
  difficulty            TEXT        NOT NULL,
  patient_name          TEXT        NOT NULL DEFAULT '',
  -- 1–5 star ratings per dimension (null = not rated)
  overall               INT         CHECK (overall               BETWEEN 1 AND 5),
  clinical_realism      INT         CHECK (clinical_realism      BETWEEN 1 AND 5),
  grading_fairness      INT         CHECK (grading_fairness      BETWEEN 1 AND 5),
  patient_communication INT         CHECK (patient_communication BETWEEN 1 AND 5),
  difficulty_accuracy   INT         CHECK (difficulty_accuracy   BETWEEN 1 AND 5),
  comment               TEXT        NOT NULL DEFAULT '',
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ratings_case_id        ON ratings (case_id);
CREATE INDEX IF NOT EXISTS ratings_user_id        ON ratings (user_id);
CREATE INDEX IF NOT EXISTS ratings_system_diff    ON ratings (system, difficulty);
CREATE INDEX IF NOT EXISTS ratings_created_at     ON ratings (created_at DESC);

-- ── Row Level Security ────────────────────────────────────────────────────────

-- Cases: publicly readable, service-role-only writes
ALTER TABLE cases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "cases_public_read"
  ON cases FOR SELECT USING (true);

-- Profiles: users can read/update their own row only
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "profiles_own_read"
  ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "profiles_own_update"
  ON profiles FOR UPDATE USING (auth.uid() = id);

-- Case sessions: users can read/insert their own rows only
ALTER TABLE case_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "sessions_own_read"
  ON case_sessions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "sessions_own_insert"
  ON case_sessions FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Ratings:
--   • Anyone (incl. anonymous) can insert
--   • Authenticated users can read their own rows
--   • Service role key (used server-side) bypasses RLS → sees everything
ALTER TABLE ratings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "ratings_anyone_insert"
  ON ratings FOR INSERT WITH CHECK (true);
CREATE POLICY "ratings_user_read"
  ON ratings FOR SELECT USING (auth.uid() = user_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- To grant yourself admin role after creating your account, run:
--   UPDATE profiles SET role = 'admin' WHERE id = '<your-user-uuid>';
-- To grant yourself pro tier:
--   UPDATE profiles SET tier = 'pro' WHERE id = '<your-user-uuid>';
-- Find your UUID at: Authentication → Users in the Supabase dashboard.
-- ─────────────────────────────────────────────────────────────────────────────
